---
default:
  source_path: app/webpacker
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
  additional_paths: &1
  - vendor
  - app/webpacker/css
  - app/webpacker/fonts
  - app/webpacker/images
  - engines/web/app/assets/stylesheets
  - app/components
  cache_manifest: false
  extract_css: true
  javascript_transpiler: swc
development:
  source_path: app/webpacker
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
  additional_paths: *1
  cache_manifest: false
  extract_css: true
  compile: true
  dev_server:
    host: localhost
    port: 3035
    hmr: false
    client:
      overlay: false
    compress: true
    allowed_hosts: all
    pretty: true
    headers:
      Access-Control-Allow-Origin: "*"
    static:
      watch:
        ignored:
        - "**/node_modules/**"
        - "**/*.swp"
  javascript_transpiler: swc
test:
  source_path: app/webpacker
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs-test
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
  additional_paths: *1
  cache_manifest: false
  extract_css: true
  compile: true
  compiler_strategy: mtime
  javascript_transpiler: swc
production:
  source_path: app/webpacker
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
  additional_paths: *1
  cache_manifest: true
  extract_css: true
  compile: false
  javascript_transpiler: swc
